### PR TITLE
Next Update list [final]

### PR DESCRIPTION
**Pull request by USERSATOSHI**
## Type
- [x] Bug Fix $fileSize , $messageSlice , $reactionCollector
- [x] Functions: $vcSize , $serverleaderboard, $readFile,$writeFile, $renameFile ,$handleError,$oldVariable , $newVariable , $oldApplicationCmd , $newApplicationCmd, $interactionData,$filterTextSplitElement
- [x] Callbacks: onFunctionError(), onVariableCreate(), onVariableUpdate(),onVariableDelete(),onApplicationCmdCreate(), onApplicationCmdUpdate(), onApplicationCmdDelete() 
- [x] Handlers: handlers for callbacks , caching system 
- [x] Others: new option in Client class (applicationCache) , added args property to $djseval

Dependencies (Third Party Modules) needed: <Name | Github Link> (Maximum: 20MB~ size)

Want a credit? Discord tag or other social media link: Ayaka#5057

Referenced Issue: #NaN (Answer for an issue, if any)

## Description
**Note: (op) => optional field**
```
$vcSize[channels/users/songs; guildID/all]
channel: returns the total channels the bot is in provided guild /all,
users: return users who are in same vc as bot in a guild or globally,
songs: songs in the queue in the provided guild/ global
```
```
$serverLeaderboard[var,asc/desc (op);custom Response (op);list (op);page(op)] 
```
```
$writeFile[file;data; encoding (op)]
writes the data in the file provided if file doesn't exist , it will create a new one , and if a data exists in the given file it will add the provided data below it 
```
```
$readFile[file]
Returns thr data of the file provided
```
```
$renameFile[oldname;newname]
renames the provided file to new name
```
```
$handlerError[error options]
gets data from functionError Callbacks options are in utils folder
```
```
$oldVariable[variable options]
$newVariable[variable options]
get data from variable callbacks
 ```
```
$oldApplicationCmd[application options]
$newApplicationCmd[application options]
get data from applicationCmd callbacks
```
***FIXES***
```
$fileSize : made it more accurate
```
``` 
$messageSlice : was giving errors if no args was provided
```
```
$reactionCollector : fixed `couldn't find the command (internel error)` Error when a user reacts with an emoji not present in the filter

### CODE REVIEW

**Comment by USERSATOSHI** [comment]
i will make it ready for review a bit later when I feel everything is done

**Review by Kino7916 — CHANGES_REQUESTED** [review]
Redirection to one module to another is a bad approach and wasteful resource. Try using the handler directly instead of using events folder.

**Comment by USERSATOSHI** [comment]
> Redirection to one module to another is a bad approach and wasteful resource. Try using the handler directly instead of using events folder.

ok i am changing that

**Comment by USERSATOSHI** [comment]
> Can you list and describe the new functions?
> 
> Any examples of function usage, result, and description may be used for answers.

i added more description is this fine now ? @Kino7916

**Comment by USERSATOSHI** [comment]
> Redirection to one module to another is a bad approach and wasteful resource. Using the handler directly is best to do.

@Kino7916 now required to handler directly

**Comment by USERSATOSHI** [comment]
some error happened in 2 codes (serverleaderboard and vcsize) that were previously working

checking for issue

**Comment by USERSATOSHI** [comment]
This is in draft now I am adding one more function to slash cause it's needed for now

**Comment by falsisdev** [comment]
they are very nice 🤩

**Comment by USERSATOSHI** [comment]
addition of new cmd completed 

it's gets the interaction data from interaction created between user and client (basically when someone do /cmd)

usage : 
$interactionData[property]

example : $interactionData[options[0].value]

live usage example:
https://user-images.githubusercontent.com/73595362/118804665-9bae7500-b8c2-11eb-9300-58176798173a.mp4

**Comment by USERSATOSHI** [comment]
Add a new function 
here is the Usage
$filterTextSplitElement

**Comment by USERSATOSHI** [comment]
Added a new function

Usage: 
$filterTextSplitElement

**Comment by USERSATOSHI** [comment]
Ready for review now

**Pull request merged**
