### PR TITLE
cpuModel and cpuPlatform

### PR DESCRIPTION
**Pull request by falsisdev**
## Type
- [x] Functions: $cpuModel and $cpuPlatform
## Description
More functions for $cpu! 2 functions returning Cpu model and Cpu Platform...

Ekran görüntüsü 2021-05-28 093357

### CODE REVIEW

**Comment by falsisdev** [comment]
i deleted an old pr. please ignore it xd

**Comment by USERSATOSHI** [comment]
ur parse.js has conflicts
did u added a old patch?

**Comment by falsisdev** [comment]
> ur parser.js has conflicts
> did u added a old patch?

mm no, i used the latest patch

**Comment by falsisdev** [comment]
Yes, now indeed conflicts are resolved.

**Pull request closed without merging**
