### PR TITLE
Utility Functions

### PR DESCRIPTION
**Pull request by DevSpen**
## Type
- [x] Functions:
  - `$isChannelManageable[channelID]`
  - `$removeAttachments[channelID;messageID]`
  - `$isVideoOn[userID]`
  - `$isStreaming[userID]`
  - `$isServerDeafened[userID]`
  - `$isServerMuted[userID]`
  - `$isSelfDeafened[userID]`
  - `$isSelfMuted[userID]`
  - `$readyTimestamp`
  - `$setRolePosition[roleID;newPosition]`
  - `$isRoleEditable[roleID]`
- [x] Improvements
  - 5 new properties in `$guild[]`.

Want a credit? Discord tag or other social media link: Spen#0999

## Description
New functions for utility purposes.

### CODE REVIEW

**Comment by BeastBoyADI** [comment]
Hmm u can also try making isRoleManageable

**Comment by BeastBoyADI** [comment]
As we want that for hardmute system

**Comment by DevSpen** [comment]
> Hmm u can also try making isRoleManageable

$isRoleEditable == $isRoleManageable

**Comment by AvonZzZ** [comment]
Typo at [guild.js](https://media.discordapp.net/attachments/865557297522278404/877935803089707018/20210819_202301.jpg)

**Comment by berat141** [comment]
$isDeafened and $isMuted is checks the user is server deafened or muted

**Comment by DevSpen** [comment]
> $isDeafened and $isMuted is checks the user is server deafened or muted

`$isDeafened` and `$isMuted` checks for either server or self, returns true for either.

Which is why `$isSelfMuted`, `$isServerDeafened`, etc are needed.

**Pull request closed without merging**
