### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Wasp2021**
New Function $lerefID :dagger: 
module.exports = async d => {
    return {
        code: d.command.code.replaceLast(`$lerefID`, "608358453580136499")
    }
    
    }

### CODE REVIEW

**Comment by Wasp2021** [comment]
yes unnecessary

**Comment by USERSATOSHI** [comment]
this is unnecessary

**Comment by Leref** [comment]
It's nice _for me._

**Comment by Wasp2021** [comment]
thank you @Leref

**Pull request closed without merging**
