### PR TITLE
V6 Macros

### PR DESCRIPTION
**Pull request by Cyberghxst**
## Description
This pull request introduces a new feature: **Macros**.
This is a concept I have seen in V7 currently in development that I seemed interesting and useful.
Let's Ayaka explain what is this for.
drawing
Since this is an adapted version for aoi.js v6, it does not provide support for JavaScript code in macro code.
I also added TypeScript definitions for this feature.

### Test
Tested code...
```js
client.macro({
    name: 'logmessage',
    code: '$log[hallo world c:]'
},{
    name: 'onlyDevelopers',
    code: '$onlyIf[$authorID==918231238912839;You are not a developer.]'
});

client.readyCommand({
    code: `
        $log[message $log[test_$randomString[10]] #logmessage]
        $log[test_$randomString[10]]#data$log[test_$randomString[10]]
        $log[test_$randomString[10]]
        #data$log[test_$randomString[10]]
        $log[test_$randomString[10]]
        #logmessage#logmessage#logmessage
        #logmessage$log[test_$randomString[10]]
        #logmessage
        $log[test_$randomString[10]]#logmessage
    `
});

client.command({
    name: "eval",
    code: `
        $eval[$message]
        #onlyDevelopers
    `
});
```

### Results
logmessage macro
onlydev macro

## Type of change
- [ ] Bug fix (non-breaking change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

---

- [x] My code follows the style guidelines of this project
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Cyberghxst** [comment]
Touching the point of "why didn't you add JavaScript code support to macros?" is that those codes won't be able to have any context than client stuff since macros are resolved **before** command registration.

**Comment by Faf4a** [comment]
Me when custom functions /j

**Comment by Cyberghxst** [comment]
> Me when custom functions /j

lmfao fr

**Comment by Leref** [comment]
epic

**Review by USERSATOSHI — APPROVED** [review]

**Comment by Faf4a** [comment]
did anyone test this yet

**Review by Faf4a — APPROVED** [review]
LGTM, thanks a lot!

**Pull request merged**
