### PR TITLE
Added $NSFWtype[...]

### PR DESCRIPTION
**Pull request by Darkgoatie**
## Type
- [x] Functions: \ $NSFWtype[Image-url]

Dependencies | Url | Size
- NSFWJS  | [Github Link](https://github.com/infinitered/nsfwjs) | 2.64 MB
 
Discord Tag: `Darkgoatie#6381`

## Description
Added $NSFWtype[Image-url]
Returns one of these:
Name     | Description
----------|-------------------------------------------
Drawing | safe for work drawings (including anime)
Hentai    | hentai and pornographic drawings
Neutral  | safe for work neutral images
Porn | pornographic images, sexual acts
Sexy | sexually explicit images, not pornography

### CODE REVIEW

**Comment by DiscordBond** [comment]
please send your commits to dev-branch, not master branch. @Darkgoatie 

maybe rename the function to $imageNSFW (personal opinion) xD

**Comment by Huguitis** [comment]
i like it

**Comment by Darkgoatie** [comment]
Oh okay, shall i delete this pull and create new?

**Comment by USERSATOSHI** [comment]
@Darkgoatie Ig yes

**Comment by Darkgoatie** [comment]
Transferring to Dev Branch

**Pull request closed without merging**
