### PR TITLE
authorAvatarCode parser.js changes

### PR DESCRIPTION
**Pull request by falsisdev**
authorAvatarCode parser.js changes

## Type
- [ ] Bug Fix
- [ ] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Dependencies (Third Party Modules) needed: <Name | Github Link> (Maximum: 20MB~ size)

Want a credit? Discord tag or other social media link: <DiscordTag | OtherSocialMediaLink>

Referenced Issue: #NaN (Answer for an issue, if any)

## Description
Pull Request Description Here

### CODE REVIEW

**Comment by DiscordBond** [comment]
@falsisdev for what we need this?

**Comment by falsisdev** [comment]
> @falsisdev for what we need this?

I think it might be necessary for commands like advanced user info or avatar info. we want to use aoijs instead of discordjs as much as possible

**Comment by USERSATOSHI** [comment]
i think it's best to not add cmds that are one liner in djseval 

and has more wider uses

**Comment by XzFirzal** [comment]
I see parser.js change, but no function added. Is this a suggestion?

**Comment by falsisdev** [comment]
> I see parser.js change, but no function added. Is this a suggestion?

Kino closed that pull request.

**Pull request closed without merging**
