### PR TITLE
v5.2.0 - Parser, Minor fixes, structures , new functions

### PR DESCRIPTION
**Pull request by USERSATOSHI**
## Type
- [x] Bug Fix
- [x] Functions: $archiveThread
- [] Callbacks: \<Callback Name>
- [x] Handlers: \<Handler Type>
- [x] Others: \______

Dependencies (Third Party Modules) needed: https://github.com/usersatoshi/structures

## Description
linked shards  functions to interpreter
switched cacheHandler to Structures
some minor fixes
added $archiveThread
updated automated usage parser , now works for all functions

### CODE REVIEW

**Comment by Leref** [comment]
Before accepting, the default database (dbdjs.db) will undergo a new change.
Hence it'll be `v3` upcoming.

**Comment by USERSATOSHI** [comment]
> Before accepting, the default database (dbdjs.db) will undergo a new change. Hence it'll be `v3` upcoming.

yes i am being aware of it but the v3 will still take quite a bit of time as Relational row oriented type and Ws type are still left in it

currently KeyValue and WideColumn is completed and is functional .

KeyValue is compatible with v2 data format hence it wont be affected by old database saving format , tho it still will be saving new data in the new format to ensure correct data type

**Comment by Leref** [comment]
This entire Pull Request, will completely break once I submit my commits,
I will not accept this til further notice.

**Comment by USERSATOSHI** [comment]
> This entire Pull Request, will completely break once I submit my commits, I will not accept this til further notice.

yes ik
so when u submit the commits i will git pull the changes and fix the merge changes

**Comment by Leref** [comment]
This pull request will not be accepted due to many changes that keeps occurring.
It's inconsistent of what's being added/removed.
This pull request should be spilt up to help differ changes.

**Pull request closed without merging**
