### PR TITLE
Mustafa amsy's edits

### PR DESCRIPTION
**Pull request by MustafaAmsy**
## Type
- [ ] New function
- [x] Functions: $application[option:name/id/icon/createdAt/createdTimestamp]

By MustafaAmsy#1384 and some help from Ayaka#2034

## Description
Application function to get client application options

### CODE REVIEW

**Comment by USERSATOSHI** [comment]
same things are present in client field too

**Comment by MustafaAmsy** [comment]
> same things are present in _$client_ too

This for application not for $client beacause you might create application today and create client after a month

**Comment by USERSATOSHI** [comment]
> > same things are present in _$client_ too
> 
> This for application not for $client beacause you might create application today and create client after a month

hmm k

**Review by XzFirzal — CHANGES_REQUESTED** [review]
Please resolve parser.js

**Comment by XzFirzal** [comment]
Resolve the conflicts

**Comment by DiscordBond** [comment]
@MustafaAmsy maybe make it as optional option in $commandsCount instead of own function?

**Pull request closed without merging**
