### PR TITLE
Added $allRoleCount

### PR DESCRIPTION
**Pull request by Rubenennj**
## Type
- [ X] Bug Fix
- [ ] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Dependencies (Third Party Modules) needed: <Name | Github Link> (Maximum: 20MB~ size)

Want a credit? Discord tag or other social media link: <DiscordTag | OtherSocialMediaLink>

Referenced Issue: #NaN (Answer for an issue, if any)

## Description
Pull Request Description Here

### CODE REVIEW

**Comment by dbthesecond** [comment]
Wait isn't there $roleCount that does the same

**Comment by USERSATOSHI** [comment]
> Wait isn't there $roleCount that does the same

roleCount is for current guild
while allRoleCount is for all guilds

**Comment by dbthesecond** [comment]
> ## Type
> * [ X] Bug Fix
> * [ ]  Functions: <Function Name>
> * [ ]  Callbacks: <Callback Name>
> * [ ]  Handlers: <Handler Type>
> * [ ]  Others: ______
> 
> Dependencies (Third Party Modules) needed: <Name | Github Link> (Maximum: 20MB~ size)
> 
> Want a credit? Discord tag or other social media link: <DiscordTag | OtherSocialMediaLink>
> 
> Referenced Issue: #NaN (Answer for an issue, if any)
> 
> ## Description
> Pull Request Description Here

Also why not add it in `$guild` function that would be better i guess

**Comment by dbthesecond** [comment]
> ## Type
> * [ X] Bug Fix
> * [ ]  Functions: <Function Name>
> * [ ]  Callbacks: <Callback Name>
> * [ ]  Handlers: <Handler Type>
> * [ ]  Others: ______
> 
> Dependencies (Third Party Modules) needed: <Name | Github Link> (Maximum: 20MB~ size)
> 
> Want a credit? Discord tag or other social media link: <DiscordTag | OtherSocialMediaLink>
> 
> Referenced Issue: #NaN (Answer for an issue, if any)
> 
> ## Description
> Pull Request Description Here

So why not add it in `$client` function

**Pull request closed without merging**
