### PR TITLE
Adding DM & NSFW Properties of `$createApplicationCommand` Function

### PR DESCRIPTION
**Pull request by Neodevils**
## Type

- [x] Function: `$createApplicationCommand[]`

## Description

Now, the commands will be avaliable on nsfw channels too, if this is specified as "true".

### CODE REVIEW

**Review by USERSATOSHI — APPROVED** [review]
LGTM


Edited: *it was not LGTM*

**Review by USERSATOSHI — CHANGES_REQUESTED** [review]
Actually i just saw memberPermissions takes perms as value instead of boolean @Neodevils

**Comment by Neodevils** [comment]
> Actually i just saw memberPermissions takes perms as value instead of boolean @Neodevils

So you are telling me to leave it empty or user uses PermissionsFlagBits?

**Comment by USERSATOSHI** [comment]
> > Actually i just saw memberPermissions takes perms as value instead of boolean @Neodevils
> 
> So you are telling me to leave it empty or user uses PermissionsFlagBits?

users with use the Perms format according to aoijs you can see $hasPerms to see how aoijs converts them

**Comment by Neodevils** [comment]
Due v7 is coming out soon, this pull request is **closed.**

**Pull request closed without merging**
