### PR TITLE
Update guild.js

### PR DESCRIPTION
**Pull request by dbthesecond**
Added systemChannel and afkChannel property to return systemchannel id and afkchannel id

## Type
- [ ] Bug Fix
- [x] Functions: $guild
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Dependencies (Third Party Modules) needed: <Name | Github Link> (Maximum: 20MB~ size)

Want a credit? Discord tag or other social media link: `BEAST#0001`

Referenced Issue: #NaN (Answer for an issue, if any)

## Description
Pull Request Description Here

### CODE REVIEW

**Comment by USERSATOSHI** [comment]
@dbthesecond add other channels too ig

**Comment by dbthesecond** [comment]
> @dbthesecond add other channels too ig

You mean news channel , rules channel and updates channel ?

**Comment by USERSATOSHI** [comment]
yes

**Comment by dbthesecond** [comment]
Ok just a sec

**Comment by dbthesecond** [comment]
Lmfao the conflicts were due to indentation

**Comment by dbthesecond** [comment]
Ok @USERSATOSHI added updates channel and rules channel

**Pull request merged**
