### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Wasp2021**
Pls Unban Support Server Ban Reason : New Account 

ID : 867386516015415296 

Nick Name And Tag : Wasp#6874

### CODE REVIEW

**Comment by Wasp2021** [comment]
and playSong Error

**Comment by Wasp2021** [comment]
image

**Comment by USERSATOSHI** [comment]
> Pls Unban Support Server Ban Reason : New Account 
> 
> ID : 867386516015415296 
> 
> Nick Name And Tag : Wasp#6874

you are not banned
you were kicked from the server by our bot because ur account creation date is less than 2 weeks

**Comment by USERSATOSHI** [comment]
> image
> 

update to version 4.2.1

**Comment by Wasp2021** [comment]
@USERSATOSHI  I'm banned on the server right now, if you open the ban, I will join the server in 2 weeks

**Comment by Wasp2021** [comment]
thank you

**Comment by USERSATOSHI** [comment]
> @USERSATOSHI  I'm banned on the server right now, if you open the ban, I will join the server in 2 weeks
> 

there is no User with name `wasp` in ban list 

and audit logs says u were kicked

**Comment by Wasp2021** [comment]
@USERSATOSHI wait me

**Comment by Wasp2021** [comment]
discord server link is where

**Comment by Wasp2021** [comment]
I will try to login again but there is no link

**Comment by Wasp2021** [comment]
my acc creation Date : 7/21/2021, 12:44:20 PM

**Comment by USERSATOSHI** [comment]
> my acc creation Date : 7/21/2021, 12:44:20 PM
> 
> 

that's less than 2 weeks that's why u got kicked

**Comment by Wasp2021** [comment]
@USERSATOSHI Okey

**Pull request merged**
