### PR TITLE
Improved

### PR DESCRIPTION
**Pull request by Cyberghxst**
- Added support to AoiClient#command let load any command type.
- Deprecated AoiClient#eventNameCommand methods use AoiClient#command instead.
- Improved definition types file.
- Added support for autocompletion for some options in AoiClient constructor.

### CODE REVIEW

**Comment by Leref** [comment]
In the current commit, I've completely changed AoiClient and it a faster efficient way to throw TypeErrors and less cluttered.
`AoiClient#command let load any command type.` is not ideal as it wouldn't mean an entire breaking change and I am not of the method.

**Comment by Cyberghxst** [comment]
> In the current commit, I've completely changed AoiClient and it a faster efficient way to throw TypeErrors and less cluttered.
> `AoiClient#command let load any command type.` is not ideal as it wouldn't mean an entire breaking change and I am not of the method. 

Ah, I just saw what you did, it's okay for me, but also it will be good to include JSDoc comments (+ updated type definitions) to improve user experience when coding the client constructor.

**Comment by USERSATOSHI** [comment]
after the merge what was the change ? @Cyberghxst

**Comment by Cyberghxst** [comment]
> after the merge what was the change ? @Cyberghxst 

I added support to AoiClient#command allow add any command type, with command type check, thing that the actual AoiClient#addCommandType is missing, and also leref said it was breaking, but I'm pretty sure it isn't.
https://github.com/AkaruiDevelopment/aoi.js/pull/467/commits/af447c752ed0e85bada0f9093664fe501ff1d011

**Comment by Leref** [comment]
outdated, as well some of these changes aren't needed?

**Pull request closed without merging**
