### PR TITLE
$sqrt[number]

### PR DESCRIPTION
**Pull request by falsisdev**
## Type
- [x] Functions: $sqrt

## Description
Finds the square root of the entered number.
`$sqrt[num]`
```js
$sqrt[81] //9
$sqrt[2] //1.41421356237
```

### CODE REVIEW

**Comment by USERSATOSHI** [comment]
@falsisdev $math[9**2]
¯\_(ツ)_/¯

**Comment by falsisdev** [comment]
uh  😔

**Comment by falsisdev** [comment]
Do I find the square root of 81 as 81//2 xd

**Comment by USERSATOSHI** [comment]
> Do I find the square root of 81 as 81//2 xd

$math[81**(1/2)]

**Comment by falsisdev** [comment]
no because i made a code to find the square root of 81 not 9².

**Comment by falsisdev** [comment]
> > Do I find the square root of 81 as 81//2 xd
> 
> $math[81**(1/2)]

k wait

**Comment by falsisdev** [comment]
> > Do I find the square root of 81 as 81//2 xd
> 
> $math[81**(1/2)]

yes thx

**Comment by lunexdev** [comment]
Thanks for adding this, it's very nice!

**Comment by falsisdev** [comment]
Ah but I guess it was already done and I'm sorry about that :(

**Comment by peach-sb** [comment]
Cool function

**Comment by lunexdev** [comment]
> A function that can be done with Math.sqrt(key)

**Comment by USERSATOSHI** [comment]
> 
> > A function that can be done with Math.sqrt(key)

or $math[$message**2]
or $djsEval[4**2;yes]

**Comment by falsisdev** [comment]
Ok, no need 😄

**Comment by BeastBoyADI** [comment]
Still i liked his efforts and am using it for my bot. Good job bro :)

**Comment by falsisdev** [comment]
very thx ♥️😄

**Pull request closed without merging**
