### PR TITLE
Update createFunction types

### PR DESCRIPTION
**Pull request by Cyberghxst**
## Description
It's me again, with a new type feature, now fixing createFunction method of FunctionManager class.
This PR adds proper typings to that method, basically all structure relies on custom function types to be one or another function type.

## Type of change
- [ ] Bug fix (non-breaking change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

- [x] My code follows the style guidelines of this project
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by MrShidoKageno — COMMENTED** [review]
👍

**Comment by Faf4a** [comment]
You truly love typings.

**Review by Faf4a — APPROVED** [review]
LGTM, thanks!

**Comment by Cyberghxst** [comment]
> You truly love typings.

this package should be properly typed for pretty cool development experience 🙂

**Pull request merged**
