### PR TITLE
Fixed playSpotify crashing

### PR DESCRIPTION
**Pull request by Rubenennj**
## Type
- [ ] Bug Fix
- [ ] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Dependencies (Third Party Modules) needed: <Name | Github Link> (Maximum: 20MB~ size)

Want a credit? Discord tag or other social media link: <DiscordTag | OtherSocialMediaLink>

Referenced Issue: #NaN (Answer for an issue, if any)

## Description
Pull Request Description Here

### CODE REVIEW

**Comment by Leref** [comment]
Though it's using ytdl to fetch songs.
Basically Spotify acts like YouTube searching all songs.
Some cases it may or not return an error.

**Comment by Rubenennj** [comment]
That doesnt change the fact info is not defined lol

**Comment by Leref** [comment]
Neither will it really solve the issue.

**Comment by Rubenennj** [comment]
info.duration() tries to can a function inside `obj` var, hence why i thought it would be obj instead of *info* though i could be wrong, but info still isnt coming nor defined anywhere

**Comment by Rubenennj** [comment]
It might be defined in a different file yeah, but variables are not defined across files /shrug

**Comment by Leref** [comment]
in the `playSpotify.js` file.

    publisher: () => video.author.name,
		publisher_url: () => video.author.url,
		userID: () => d.message.author.id,
		url: () => video.url,
		stream: "ytdl",
		prune: false

It's still picking as a STREAM.
Using ytdl, even if it's define, the error cannot be stopped.
There's also another handler about this `SpotifySearchHandler`
It should still pick up video details but how this function is even coded is poorly made and isn't designed well.
I can accept the merge but if there's a huge query of songs, it'll break.

**Pull request merged**
