### PR TITLE
setInterval

### PR DESCRIPTION
**Pull request by equlon**
Add new function $setInterval

### CODE REVIEW

**Comment by DiscordBond** [comment]
Is this a suggestion? @equlon

**Comment by USERSATOSHI** [comment]
Bot.loopCommand exist @equlon

**Comment by equlon** [comment]
> Is this a suggestion? @equlon

Yes

**Comment by equlon** [comment]
> Bot.loopCommand exist @equlon

Who brought it up?

**Comment by DiscordBond** [comment]
> > Bot.loopCommand exist @equlon
> 
> Who brought it up?

It was added in 2.1.0 back in February @equlon

**Comment by equlon** [comment]
> > > Bot.loopCommand exist @equlon
> > 
> > 
> > Who brought it up?
> 
> It was added in 2.1.0 back in February @equlon

I didn't think of it anyway, but $setInterval as much as any I didn't mean it anyway but $setInterval like every how many seconds a bot to make a certain function like Aoi.JS Master Bot coin drops random

**Comment by USERSATOSHI** [comment]
> > > > Bot.loopCommand exist @equlon
> > > 
> > > 
> > > Who brought it up?
> > 
> > It was added in 2.1.0 back in February @equlon
> 
> I didn't think of it anyway, but $setInterval as much as any I didn't mean it anyway but $setInterval like every how many seconds a bot to make a certain function like Aoi.JS Master Bot coin drops random 

that can be achieved using bot.loopCommand pretty easily

read the docs of loopCommand

**Comment by Kino7916** [comment]
This kind of function already possible with existing callback, Closed PR.

**Pull request closed without merging**
