### PR TITLE
New function $findLinks

### PR DESCRIPTION
**Pull request by geronimostar**
`module.exports = async (d) => {

    let inside = d.unpack()

    let code = d.command.code

    
    let error = d.inside(inside)

    if (error) return d.error(error)

  
    const [ content, separator = ', ' ] = inside.splits
    return {

        code: code.replaceLast(`$findLinks${inside}`, content.split(' ').filter(x => x.startsWith("https://")).join(separator))

    }

}  
`
It can be used to find links (as the name suggests) from a given text with a optional separator field. Default separator is ,

### CODE REVIEW

**Comment by USERSATOSHI** [comment]
> `module.exports = async (d) => {
> 
>     let inside = d.unpack()
> 
>     let code = d.command.code
> 
>     
>     let error = d.inside(inside)
> 
>     if (error) return d.error(error)
> 
>   
>     const [ content, separator = ', ' ] = inside.splits
>     return {
> 
>         code: code.replaceLast(`$findLinks${inside}`, content.split(' ').filter(x => x.startsWith("https://")).join(separator))
> 
>     }
> 
> }  
> `
> It can be used to find links (as the name suggests) from a given text with a optional separator field. Default separator is , 

textsplit + filterTextSplitElement 
that's all 

so no need of a new Function

**Comment by Alconera130** [comment]
> `module.exports = async (d) => {
> 
> ```
> let inside = d.unpack()
> 
> let code = d.command.code
> 
> 
> let error = d.inside(inside)
> 
> if (error) return d.error(error)
> 
> 
> const [ content, separator = ', ' ] = inside.splits
> return {
> 
>     code: code.replaceLast(`$findLinks${inside}`, content.split(' ').filter(x => x.startsWith("https://")).join(separator))
> 
> }
> ```
> 
> }  
> `
> It can be used to find links (as the name suggests) from a given text with a optional separator field. Default separator is ,

isnt that...

**Comment by BeastBoyADI** [comment]
> > `module.exports = async (d) => {
> > ```
> > let inside = d.unpack()
> > 
> > let code = d.command.code
> > 
> > 
> > let error = d.inside(inside)
> > 
> > if (error) return d.error(error)
> > 
> > 
> > const [ content, separator = ', ' ] = inside.splits
> > return {
> > 
> >     code: code.replaceLast(`$findLinks${inside}`, content.split(' ').filter(x => x.startsWith("https://")).join(separator))
> > 
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }  
> > `
> > It can be used to find links (as the name suggests) from a given text with a optional separator field. Default separator is ,
> 
> textsplit + filterTextSplitElement
> that's all
> 
> so no need of a new Function

The easy way is $replaceText and $removeLinks. Like u can do $replaceText[$message;$removeLinks[$message];] which will return the link itself

**Comment by USERSATOSHI** [comment]
> > > `module.exports = async (d) => {
> > > ```
> > > let inside = d.unpack()
> > > 
> > > let code = d.command.code
> > > 
> > > 
> > > let error = d.inside(inside)
> > > 
> > > if (error) return d.error(error)
> > > 
> > > 
> > > const [ content, separator = ', ' ] = inside.splits
> > > return {
> > > 
> > >     code: code.replaceLast(`$findLinks${inside}`, content.split(' ').filter(x => x.startsWith("https://")).join(separator))
> > > 
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > }  
> > > `
> > > It can be used to find links (as the name suggests) from a given text with a optional separator field. Default separator is ,
> > 
> > textsplit + filterTextSplitElement
> > that's all
> > 
> > so no need of a new Function
> 
> The easy way is $replaceText and $removeLinks. Like u can do $replaceText[$message;$removeLinks[$message];] which will return the link itself

that will Only work if the link(s) is at beginning or at end of message

if it's in between
then this won't work 
@BeastBoyADI

**Comment by BeastBoyADI** [comment]
Hmm i didn't thought that but ok. Still $textSplit would do the work

**Comment by USERSATOSHI** [comment]
> Hmm i didn't thought that but ok. Still $textSplit would do the work

yup textsplit + filterTextSplitElement

**Pull request closed without merging**
