### PR TITLE
New function & parser.js update

### PR DESCRIPTION
**Pull request by TheMarci**
## Type
- [ ] Bug Fix
- [x] Functions: \ $editGuild (made by me and Der Bond#1271)
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [x] Others: \Updated parser.js

Dependencies (Third Party Modules) needed: Not needed

Want a credit? Discord tag or other social media link: TheMarci#3490, Der Bond#1271

Referenced Issue: #NaN 

## Description
$editGuild[option;result;guildID (optional)] - A compact function to edit different server settings (made by me and Der Bond#1271)

Updated parser.js for the new functions.

### CODE REVIEW

**Comment by DiscordBond** [comment]
Can you rename it to $setAFKChannel and $setAFKTimeout? 
That's shorter ^^

**Comment by TheMarci** [comment]
> Can you rename it to $setAFKChannel and $setAFKTimeout?
> That's shorter ^^

Of course!

**Comment by TheMarci** [comment]
Added 2 more functions.
$isVerified
$isPartnered

**Comment by DiscordBond** [comment]
$guild[guildId;ispartnered] and $guild[guildId;isverified] already exist

**Comment by DiscordBond** [comment]
But why the two new functions need channel ID option? Partner/Verified is Guild based, not channel based

**Comment by TheMarci** [comment]
> But why the two new functions need channel ID option? Partner/Verified is Guild based, not channel based

Oops thats not what I wanted to write sorry. I meant guildID. But nevermind I delete it if it exists. Tho I didn't know it exists.

**Comment by TheMarci** [comment]
Added 3 functions:
$setVerifyLevel
$setExplicitFilter
$setSystemChannel
(I looked through the functions and I didn't find these so I hope they don't already exists lol)

**Comment by DiscordBond** [comment]
name it $setContentFilter instead of $setExplicitFilter, okay?
Also you forgot the "m" inside 15m in $setAFKTimeout

**Comment by TheMarci** [comment]
> name it $setContentFilter instead of $setExplicitFilter, okay?
> Also you forgot the "m" inside 15m in $setAFKTimeout

Renamed it and fixed the "m"! Also I just noticed the error message was wrong too in afktimeout so I fixed that too.

**Comment by TheMarci** [comment]
This new function $editGuild is made by me and Der Bond#0001 !

**Comment by Kino7916** [comment]
Listing created functions would be much appreciated.

**Comment by TheMarci** [comment]
> Listing created functions would be much appreciated.

What do you mean? I made functoins for guild editing but then me and Der Bond made the compact $editGuild function so I deleted the my single functions. So right now it's just one function here. No more.

**Pull request merged**
