### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Neodevils**
Updated it for v6.1.x

### CODE REVIEW

**Comment by ghost** [comment]
Please add way to set a user variable same in every server. $setUserVar sets user variable for current or specified server but I want that we can set a user's variable for every same. So please bring this function in next update.

**Comment by Neodevils** [comment]
> Please add way to set a user variable same in every server. $setUserVar sets user variable for current or specified server but I want that we can set a user's variable for every same. So please bring this function in next update.

Hello @Saksh2022 . I don't know how it is related to my pull request, but you can use `$setGlobalUserVar` for that. Have a nice day!

**Comment by ghost** [comment]
Wait what, by mistaken  I commented on your pull request. Ok I got a way for it $setGlobalUserVar. Thanks!

**Comment by Leref** [comment]
These methods have been pushed later onto future versions.

**Comment by Neodevils** [comment]
> These methods have been pushed later onto future versions.

So on v7?

**Pull request closed without merging**
